// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'package:flutter/material.dart';

class LightColor {
  static const Color amberglow = Color.fromRGBO(249, 138, 55, 1);

  static const Color ferngreen = Color.fromRGBO(18, 116, 83, 1);

  static const Color moonstone = Color.fromRGBO(248, 247, 243, 1);

  static const Color shadowed = Color.fromRGBO(44, 39, 36, 1);

  static const Color inferno = Color.fromRGBO(242, 30, 30, 1);

  static const Color silvershine = Color.fromRGBO(235, 235, 231, 1);

  static const Color graphite = Color.fromRGBO(106, 106, 106, 1);

  static const Color snowfall = Color.fromRGBO(255, 255, 255, 1);
}
