// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'package:flutter/material.dart';
import 'color.dart';

class CustomTheme extends ThemeExtension<CustomTheme> {
  const CustomTheme({
    required this.amberglow,
    required this.ferngreen,
    required this.moonstone,
    required this.shadowed,
    required this.inferno,
    required this.silvershine,
    required this.graphite,
    required this.snowfall,
  });

  final Color amberglow;

  final Color ferngreen;

  final Color moonstone;

  final Color shadowed;

  final Color inferno;

  final Color silvershine;

  final Color graphite;

  final Color snowfall;

  @override
  CustomTheme copyWith({
    Color? amberglow,
    Color? ferngreen,
    Color? moonstone,
    Color? shadowed,
    Color? inferno,
    Color? silvershine,
    Color? graphite,
    Color? snowfall,
  }) {
    return CustomTheme(
      amberglow: amberglow ?? this.amberglow,
      ferngreen: ferngreen ?? this.ferngreen,
      moonstone: moonstone ?? this.moonstone,
      shadowed: shadowed ?? this.shadowed,
      inferno: inferno ?? this.inferno,
      silvershine: silvershine ?? this.silvershine,
      graphite: graphite ?? this.graphite,
      snowfall: snowfall ?? this.snowfall,
    );
  }

//list of themes
  static const CustomTheme light = CustomTheme(
    amberglow: LightColor.amberglow,
    ferngreen: LightColor.ferngreen,
    moonstone: LightColor.moonstone,
    shadowed: LightColor.shadowed,
    inferno: LightColor.inferno,
    silvershine: LightColor.silvershine,
    graphite: LightColor.graphite,
    snowfall: LightColor.snowfall,
  );

  @override
  ThemeExtension<CustomTheme> lerp(
    ThemeExtension<CustomTheme>? other,
    double t,
  ) {
// TODO: implement lerp
    throw UnimplementedError();
  }
}
