// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

class CustomTypography {
  CustomTypography(this.color);
  factory CustomTypography.fromColor(Color color) {
    return CustomTypography(color);
  }
  final Color color;
//List of textstyles
  TextStyle get k24Bold => GoogleFonts.sourceSans3(
        fontSize: 24,
        color: color,
        fontWeight: FontWeight.w700,
      );
  TextStyle get k16SemiBold => GoogleFonts.sourceSans3(
        fontSize: 16,
        color: color,
        fontWeight: FontWeight.w600,
      );
  TextStyle get k36Bold => GoogleFonts.sourceSans3(
        fontSize: 36,
        color: color,
        fontWeight: FontWeight.w700,
      );
  TextStyle get k14Reg => GoogleFonts.sourceSans3(
        fontSize: 14,
        color: color,
        fontWeight: FontWeight.w400,
      );
  TextStyle get k20Bold => GoogleFonts.sourceSans3(
        fontSize: 20,
        color: color,
        fontWeight: FontWeight.w600,
      );
  TextStyle get k16Reg => GoogleFonts.sourceSans3(
        fontSize: 16,
        color: color,
        fontWeight: FontWeight.w400,
      );
}
