// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'package:flutter/material.dart';
import 'package:gap/gap.dart';
import 'package:get/get.dart';

import '../../service/network_service.dart';
import '../../service/theme_service.dart';
import '../../theme/theme.dart';
import '../../theme/typography.dart';
import '../../util/util.dart';
import '../../widgets/custom_scaffold.dart';
import '../../widgets/dinasona_button.dart';

class LostConnectionPage extends StatelessWidget {
  const LostConnectionPage({super.key});

  @override
  Widget build(BuildContext context) {
    final CustomTheme theme = Get.put(ThemeService()).theme;
    return PopScope(
      canPop: false,
      child: CustomScaffold(
        body: Padding(
          padding: EdgeInsets.symmetric(
            horizontal: getRelativeWidth(20),
            vertical: getRelativeHeight(70),
          ),
          child: Column(
            children: <Widget>[
              Image.asset(
                'assets/images/logos/dinasona_logo.png',
                scale: 2.5,
              ),
              SizedBox(height: getRelativeHeight(150)),
              Text(
                'Connection lost'.tr,
                style: CustomTypography.fromColor(theme.shadowed).k36Bold,
              ),
              Gap(getRelativeHeight(10)),
              Text(
                "Uh-oh! It seems like you're not connected to the internet. Please check your connection and try again"
                    .tr,
                style: CustomTypography.fromColor(theme.graphite).k16Reg,
                textAlign: TextAlign.center,
              ),
              SizedBox(height: getRelativeHeight(57)),
              DinasonaButton(
                text: 'Retry connection',
                onPressed: () async {
                  final bool hasInternet = await Get.find<ConnectivityService>()
                      .hasInternetConnection();
                  if (hasInternet) {
                    Get.back();
                  } else {
                    Get.snackbar(
                      'No internet connection'.tr,
                      'Please check your connection and try again'.tr,
                    );
                  }
                },
                color: theme.amberglow,
              ),
              SizedBox(height: getRelativeHeight(37)),
            ],
          ),
        ),
      ),
    );
  }
}
