// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch
import '../base/auth_service_base.dart';
import '../model/auth_result.dart';

class AuthService extends AuthServiceBase {
  // Login with Google.
  Future<AuthResponse> googleSignIn() async {
    return AuthResponse(
      result: <String, dynamic>{},
      accessToken: 'Not Implemented',
      message: 'Not Implemented',
      status: -1,
      success: false,
    );
  }

  // Login with Apple.
  Future<AuthResponse> appleSignIn({
    String? authorizationCode,
    String? identityToken,
  }) async {
    return AuthResponse(
      result: <String, dynamic>{},
      accessToken: 'Not Implemented',
      message: 'Not Implemented',
      status: -1,
      success: false,
    );
  }
}
