// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';

import '../model/language_model.dart';
import 'storage/storage_service.dart';

class LocalizationController extends GetxController implements GetxService {
  final StorageService storageService = Get.find<StorageService>();
  bool defaulLanguage = true;
  bool defaultCurrencie = true;

  Map<String, String> selectedCurrency = <String, String>{
    'name': 'Swiss Frank',
    'code': 'CHF',
    'sign': 'CHF',
    'image': 'assets/images/switzerland.png',
  };

  final List<Map<String, String>> supportedCurrencies = <Map<String, String>>[
    <String, String>{
      'name': 'Swiss Frank',
      'code': 'CHF',
      'sign': 'CHF',
      'image': 'assets/images/switzerland.png',
    },
    <String, String>{
      'name': 'Australian Dollar',
      'code': 'AUD',
      'sign': r'AU$',
      'image': 'assets/images/australia.png',
    },
    <String, String>{
      'name': 'British Pound',
      'code': 'GBP',
      'sign': '£',
      'image': 'assets/images/great_britain.png',
    },
    <String, String>{
      'name': 'Canadian Dollar',
      'code': 'CAD',
      'sign': r'CA$',
      'image': 'assets/images/canada.png',
    }
  ];

  Map<String, Map<String, String>> translations =
      <String, Map<String, String>>{};
  Locale get locale => _locale;
  final List<LanguageModel> supportedLanguageList = <LanguageModel>[
    LanguageModel(
      imageUrl: '🇺🇸',
      languageName: 'English',
      languageCode: 'en',
      countryCode: 'US',
    ),
  ];
  Locale _locale = const Locale(
    'en',
    'US',
  );
  Future<void> init() async {
    _loadCurrency();
    _loadLanguage();
    await _loadTranslations();
  }

  Future<void> _loadTranslations() async {
    for (final LanguageModel languageModel in supportedLanguageList) {
      final String jsonStringValues = await rootBundle
          .loadString('assets/locale/${languageModel.languageCode}.json');
      final Map<String, dynamic> mappedJson =
          jsonDecode(jsonStringValues) as Map<String, dynamic>;
      final Map<String, String> json = <String, String>{};
      mappedJson.forEach((String key, dynamic value) {
        json[key] = value.toString();
      });
      translations[
          '${languageModel.languageCode}_${languageModel.countryCode}'] = json;
    }
  }

  //change currency
  Future<void> changeCurrency(String currency) async {
    await storageService.shared.writeString('currency', currency);
    defaultCurrencie = false;
  }

  //load currency
  void _loadCurrency() {
    try {
      final String currency = storageService.shared.readString('currency');
      if (currency.isNotEmpty) {
        defaultCurrencie = false;
      }
    } catch (_) {}
  }

  Future<void> changeLanguage(LanguageModel languageModel) async {
    final Locale newLocale =
        Locale(languageModel.languageCode, languageModel.countryCode);
    _locale = newLocale;
    await storageService.shared
        .writeString('language', languageModel.toJson().toString());
    defaulLanguage = false;
  }

  void _loadLanguage() {
    try {
      final String languageString =
          storageService.shared.readString('language');
      final LanguageModel languageModel = LanguageModel.fromJson(
        jsonDecode(languageString) as Map<String, dynamic>,
      );
      final Locale newLocale =
          Locale(languageModel.languageCode, languageModel.countryCode);
      _locale = newLocale;
      defaulLanguage = false;
    } catch (_) {}
  }
}
