// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:get/get.dart';

import '../model/currency_model.dart';
import '../model/language_model.dart';
import 'storage/storage_service.dart';
import 'user_state_service.dart';

class LocalizationController extends GetxController implements GetxService {
  final StorageService storageService = Get.find<StorageService>();
  bool defaulLanguage = true;
  bool defaultCurrencie = true;
  Rx<CurrencyModel> selectedCurrency = CurrencyModel(
    name: 'Swiss Franc',
    code: 'CHF',
    sign: 'CHF',
    image: 'assets/images/switzerland.png',
  ).obs;

  final List<CurrencyModel> supportedCurrencies = <CurrencyModel>[
    CurrencyModel(
      name: 'Australian Dollar',
      code: 'AUD',
      sign: r'AU$',
      image: 'assets/images/australia.png',
    ),
    CurrencyModel(
      name: 'Swiss Franc',
      code: 'CHF',
      sign: 'CHF',
      image: 'assets/images/switzerland.png',
    ),
    CurrencyModel(
      name: 'British Pound',
      code: 'GBP',
      sign: '£',
      image: 'assets/images/great_britain.png',
    ),
    CurrencyModel(
      name: 'Canadian Dollar',
      code: 'CAD',
      sign: r'CA$',
      image: 'assets/images/canada.png',
    ),
  ];

  Future<void> getUserCurrencyFromBackend() async {
    await Get.find<UserStateService>().fetchUserInfo();
    final String savedCurrency =
        Get.find<UserStateService>().user.value.currency.toLowerCase();

    if (savedCurrency == '') {
      await Get.find<UserStateService>().updateUserInfo(<String, String>{
        'currency': selectedCurrency.value.code.toLowerCase(),
      });
    } else {
      selectedCurrency.value = supportedCurrencies.firstWhere(
        (CurrencyModel element) => element.code.toLowerCase() == savedCurrency,
      );
    }
  }

  Map<String, Map<String, String>> translations =
      <String, Map<String, String>>{};
  Locale get locale => _locale;
  final List<LanguageModel> supportedLanguageList = <LanguageModel>[
    LanguageModel(
      imageUrl: '🇺🇸',
      languageName: 'English',
      languageCode: 'en',
      countryCode: 'US',
    ),
  ];
  Locale _locale = const Locale(
    'en',
    'US',
  );
  Future<void> init() async {
    _loadCurrency();
    _loadLanguage();
    await _loadTranslations();
  }

  Future<void> _loadTranslations() async {
    for (final LanguageModel languageModel in supportedLanguageList) {
      final String jsonStringValues = await rootBundle
          .loadString('assets/locale/${languageModel.languageCode}.json');
      final Map<String, dynamic> mappedJson =
          jsonDecode(jsonStringValues) as Map<String, dynamic>;
      final Map<String, String> json = <String, String>{};
      mappedJson.forEach((String key, dynamic value) {
        json[key] = value.toString();
      });
      translations[
          '${languageModel.languageCode}_${languageModel.countryCode}'] = json;
    }
  }

  //change currency
  Future<void> changeCurrency(String currency) async {
    await storageService.shared.writeString('currency', currency);
    defaultCurrencie = false;
  }

  //load currency
  void _loadCurrency() {
    try {
      final String currency = storageService.shared.readString('currency');
      if (currency.isNotEmpty) {
        defaultCurrencie = false;
      }
    } catch (_) {}
  }

  Future<void> changeLanguage(LanguageModel languageModel) async {
    final Locale newLocale =
        Locale(languageModel.languageCode, languageModel.countryCode);
    _locale = newLocale;
    await storageService.shared
        .writeString('language', languageModel.toJson().toString());
    defaulLanguage = false;
  }

  void _loadLanguage() {
    try {
      final String languageString =
          storageService.shared.readString('language');
      final LanguageModel languageModel = LanguageModel.fromJson(
        jsonDecode(languageString) as Map<String, dynamic>,
      );
      final Locale newLocale =
          Locale(languageModel.languageCode, languageModel.countryCode);
      _locale = newLocale;
      defaulLanguage = false;
    } catch (_) {}
  }
}
