// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'package:get/get.dart';

import '../pages/page_laoder/controllers/page_loader_controller.dart';
import 'logger_service.dart';
import 'storage/secure_storage_service.dart';
import 'storage/shared_storage_service.dart';
import 'storage/storage_service.dart';

class MainBindings extends Bindings {
  @override
  Future<void> dependencies() async {
    //inject services and controllers
    _injectServices();
    _injectControllers();
  }

  void _injectServices() {
    //Services injection

    Get
      ..lazyPut(LoggerService.new)
      ..lazyPut(SecureStorageService.new)
      ..lazyPut(SharedStorageService.new)
      ..lazyPut(StorageService.new);
  }

  void _injectControllers() {
    //Controllers injection
    Get.lazyPut(PageLoaderController.new, fenix: true);
  }
}
