// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'package:get/get.dart';

import '../pages/add/controllers/add_page_controller.dart';
import '../pages/donate/controllers/donate_page_controller.dart';
import '../pages/home/controllers/beneficary_home_page_controller.dart';
import '../pages/home/controllers/donor_home_page_controller.dart';
import '../pages/profile/controllers/beneficiary_profile_page_controller.dart';
import '../pages/profile/controllers/donor_profile_page_controller.dart';
import '../pages/root/controllers/beneficiary_root_controller.dart';
import '../pages/root/controllers/donor_root_page_controller.dart';
import '../pages/wallet/controllers/wallet_page_controller.dart';
import 'logger_service.dart';
import 'storage/secure_storage_service.dart';
import 'storage/shared_storage_service.dart';
import 'storage/storage_service.dart';
import 'wallet_service.dart';

class MainBindings extends Bindings {
  @override
  Future<void> dependencies() async {
    //inject services and controllers
    _injectServices();
    _injectControllers();
  }

  void _injectServices() {
    //Services injection

    Get
      ..lazyPut(LoggerService.new)
      ..lazyPut(SecureStorageService.new)
      ..lazyPut(SharedStorageService.new)
      ..lazyPut(StorageService.new);
  }

  void _injectControllers() {
    //Controllers injection
    Get
      ..lazyPut(DonorRootController.new, fenix: true)
      ..lazyPut(BeneficiaryRootController.new, fenix: true)
      ..lazyPut(DonorHomePageController.new, fenix: true)
      ..lazyPut(BeneficiaryHomePageController.new, fenix: true)
      ..lazyPut(DonorProfilePageController.new, fenix: true)
      ..lazyPut(BeneficiaryProfilePageController.new, fenix: true)
      ..lazyPut(WalletPageController.new, fenix: true)
      ..lazyPut(AddPageController.new, fenix: true)
      ..lazyPut(DonatePageController.new, fenix: true);
  }
}
