// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../theme/theme.dart';
import 'storage_service.dart';

class ThemeService extends GetxService {
  final StorageService _storage = Get.find<StorageService>();
  ThemeData get themeData => _getThemeData();

  CustomTheme get theme => Get.theme.extension<CustomTheme>()!;

  ThemeData _getThemeData() {
    final String theme = _getSavedTheme();

    switch (theme) {
      //List of themes

      case 'light':
        return ThemeData(
          extensions: const <ThemeExtension<CustomTheme>>[
            CustomTheme.light,
          ],
        );

      default:
        return ThemeData(
          extensions: const <ThemeExtension<CustomTheme>>[
            CustomTheme.light,
          ],
        );
    }
  }

  String _getSavedTheme() {
    String value;
    try {
      value = _storage.getString('themeMode');
    } on StorageException catch (_) {
      setTheme('light');
      value = 'light';
    }

    return value;
  }

  Future<void> setTheme(String theme) async {
    await _storage.setString('themeMode', theme);
    Get.changeTheme(_getThemeData());
  }
}
