// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'package:get/get.dart';

import '../model/user.dart';

class UserStateService extends GetxService {
  Rx<User> user = User().obs;

  void clear() {
    user.value = User();
  }
}
