// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'dart:async';
import 'dart:convert';
import 'dart:io';

import 'package:dio/dio.dart' as dio_import;
import 'package:get/get.dart';
import 'package:http/http.dart' as http;
import 'package:http_parser/http_parser.dart';

import '../model/beneficiary_statistics.dart';
import '../model/donor_statistics.dart';
import '../model/user.dart';
import '../util/constants.dart';
import 'api_service.dart';
import 'logger_service.dart';

class UserStateService extends GetxService {
  final APIService apiService = Get.find<APIService>();
  final LoggerService logger = Get.find<LoggerService>();
  Rx<User> user = User().obs;
  bool _hasBeenInitialized = false;
  final RxList userNeeds = <dynamic>[].obs;
  Rx<DonorStatistics> donorStatistics = DonorStatistics(
    totalAmountDonated: 0,
    totalCountriesDonatedTo: 0,
    totalBeneficiariesDonatedTo: 0,
  ).obs;

  Rx<BeneficiaryStatistics> beneficiaryStatistics = BeneficiaryStatistics(
    totalAmountDonated: -1,
    totalNeedsClosed: -1,
    totalPeopleDonated: -1,
  ).obs;

  Future<void> init() async {
    if (!_hasBeenInitialized) {
      await fetchUserInfo();
      if (user.value.isDonor) {
        await fetchDonorStatistics();
      } else {
        await fetchBeneficiaryStatistics();
        await fetchUserNeeds();
      }
    }
    _hasBeenInitialized = true;
  }

  void clear() {
    user.value = User();
  }

  Future<void> fetchUserNeeds() async {
    final String url =
        Uri.https(Constants.apiDomain, '/need/beneficiary/').toString();
    try {
      final dio_import.Response<dynamic> response = await dio_import.Dio().get(
        url,
        options: dio_import.Options(
          headers: <String, dynamic>{
            HttpHeaders.authorizationHeader:
                'Bearer ${apiService.authenticationToken}',
          },
        ),
      );
      if (response.statusCode == 200) {
        //print('test: ${response.data}');
        //print('test2: ${response.data[0]}');
        /* userNeeds.value = DonorStatistics.fromJson(
          jsonEncode(
            (response.data as Map<String, dynamic>)['result']
                as Map<String, dynamic>,
          ),
        ); */
      } else {
        logger.log(
          'Failed to fetch donor statistics: StatusCode: ${response.statusCode}, ${response.data}',
        );
      }
    } catch (e) {
      logger.log('Error while fetching donor statistics: $e');
    }
  }

  Future<void> fetchDonorStatistics() async {
    final String url =
        Uri.https(Constants.apiDomain, '/donation/donor/stats/').toString();
    try {
      final dio_import.Response<dynamic> response = await dio_import.Dio().get(
        url,
        options: dio_import.Options(
          headers: <String, dynamic>{
            HttpHeaders.authorizationHeader:
                'Bearer ${apiService.authenticationToken}',
          },
        ),
      );
      if (response.statusCode == 200) {
        donorStatistics.value = DonorStatistics.fromJson(
          jsonEncode(
            (response.data as Map<String, dynamic>)['result']
                as Map<String, dynamic>,
          ),
        );
      } else {
        logger.log(
          'Failed to fetch donor statistics: StatusCode: ${response.statusCode}, ${response.data}',
        );
      }
    } catch (e) {
      logger.log('Error while fetching donor statistics: $e');
    }
  }

  Future<void> fetchBeneficiaryStatistics() async {
    final String url =
        Uri.https(Constants.apiDomain, '/beneficiary/').toString();
    try {
      final dio_import.Response<dynamic> response = await dio_import.Dio().get(
        url,
        options: dio_import.Options(
          headers: <String, dynamic>{
            HttpHeaders.authorizationHeader:
                'Bearer ${apiService.authenticationToken}',
          },
        ),
      );
      if (response.statusCode == 200) {
        beneficiaryStatistics.value = BeneficiaryStatistics.fromJson(
          jsonEncode(
            (response.data as Map<String, dynamic>)['result']
                as Map<String, dynamic>,
          ),
        );
      } else {
        logger.log(
          'Failed to fetch donor statistics: StatusCode: ${response.statusCode}, ${response.data}',
        );
      }
    } catch (e) {
      logger.log('Error while fetching donor statistics: $e');
    }
  }

  Future<void> fetchUserInfo() async {
    final String url = Uri.https(Constants.apiDomain, '/user-info/').toString();
    try {
      final dio_import.Response<dynamic> response = await dio_import.Dio().get(
        url,
        options: dio_import.Options(
          headers: <String, dynamic>{
            HttpHeaders.authorizationHeader:
                'Bearer ${apiService.authenticationToken}',
          },
        ),
      );
      if (response.statusCode == 200) {
        user.value = User.fromJson(
          ((response.data as Map<String, dynamic>)['result']
              as Map<String, dynamic>)['user'] as Map<String, dynamic>,
        );
      } else {
        logger.log(
          'Failed to fetch user info: StatusCode: ${response.statusCode}, ${response.data}',
        );
      }
    } catch (e) {
      logger.log('Error while fetching user info: $e');
    }
  }

  Future<void> updateUserInfo(Map<String, dynamic> updatedUser) async {
    final String url =
        Uri.https(Constants.apiDomain, '/user-info/update/').toString();

    try {
      final http.Response response = await http.patch(
        Uri.parse(url),
        headers: <String, String>{
          HttpHeaders.authorizationHeader:
              'Bearer ${apiService.authenticationToken}',
          'Content-Type': 'application/json; charset=UTF-8',
        },
        body: jsonEncode(updatedUser),
      );

      if (response.statusCode == 200) {
        user.value = User.fromJson(
          (((jsonDecode(response.body) as Map<String, dynamic>)['result']
              as Map<String, dynamic>)['user']) as Map<String, dynamic>,
        );
        logger.log(response.body);
      } else {
        logger.log(
          'Failed to update user info: StatusCode: ${response.statusCode}, ${response.body}',
        );
      }
    } catch (e) {
      logger.log('Error while updating user info: $e');
    }
  }

  Future<bool> updateAvatar({
    required File file,
  }) async {
    final String url =
        Uri.https(Constants.apiDomain, '/user-info/update/').toString();
    try {
      final dio_import.MultipartFile multipartFile =
          await dio_import.MultipartFile.fromFile(
        file.path,
        contentType: MediaType('image', 'jpg'),
      );
      final dio_import.FormData formData =
          dio_import.FormData.fromMap(<String, dynamic>{
        'avatar': multipartFile,
      });
      final dio_import.Response<dynamic> response = await dio_import.Dio(
        dio_import.BaseOptions(
          validateStatus: (int? code) {
            return true;
          },
        ),
      ).put(
        url,
        data: formData,
        options: dio_import.Options(
          headers: <String, dynamic>{
            HttpHeaders.contentTypeHeader: 'multipart/form-data',
            HttpHeaders.authorizationHeader:
                'Bearer ${apiService.authenticationToken}',
          },
        ),
      );
      if (response.statusCode == 200) {
        await fetchUserInfo();
        logger.log('Avatar updated');
        return true;
      } else {
        logger.log(
          'Failed to update avatar: StatusCode: ${response.statusCode}, ${response.data}',
        );
        return false;
      }
    } catch (e) {
      logger.log('Error while updating avatar: $e');
      return false;
    }
  }
}
