// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'dart:async';

import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../widget/custom_scaffold.dart';
import 'who_you_are.dart';

class SplashPage extends StatelessWidget {
  const SplashPage({
    super.key,
  });
  @override
  Widget build(BuildContext context) {
    Timer(
      const Duration(seconds: 2),
      () => Get.off<void>(() => const ChosePathPage()),
    );

    return CustomScaffold(
      body: Center(
        child: Image.asset('asset/images/logo.png'),
      ),
    );
  }
}
