// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

class LanguageModel {
  LanguageModel({
    required this.imageUrl,
    required this.languageName,
    required this.countryCode,
    required this.languageCode,
  });

  factory LanguageModel.fromJson(Map<String, dynamic> json) {
    return LanguageModel(
      imageUrl: json['imageUrl'] as String,
      languageName: json['languageName'] as String,
      countryCode: json['countryCode'] as String,
      languageCode: json['languageCode'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'imageUrl': imageUrl,
      'languageName': languageName,
      'countryCode': countryCode,
      'languageCode': languageCode,
    };
  }

  String imageUrl;
  String languageName;
  String languageCode;
  String countryCode;
}
