// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'package:get/get.dart';

class Messages extends Translations {
  Messages({required this.languages});
  final Map<String, Map<String, String>> languages;

  @override
  Map<String, Map<String, String>> get keys {
    return languages;
  }
}
