// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'beneficiary.dart';

class User {
  User();

  User.fromJson(Map<String, dynamic> json)
      : id = json['id'] as int? ?? json['pk'] as int? ?? -1,
        name = json['name'] as String? ?? '',
        beneficiary = json['beneficiary'] == null
            ? Beneficiary.anonymous()
            : json['beneficiary'] is Beneficiary
                ? json['beneficiary'] as Beneficiary
                : Beneficiary.fromJson(
                    json['beneficiary'] as Map<String, dynamic>,
                  ),
        email = json['email'] as String? ?? '',
        avatar = json['avatar'] as String? ?? '',
        username = json['username'] as String? ?? '',
        firstLogin = json['is_first_login'] as bool? ?? true,
        aboutMe = json['about_me'] as String? ?? '',
        isDonor = json['is_donor'] as bool? ?? false,
        currency = json['currency'] as String? ?? '',
        country = json['country_string'] as String? ?? '';

  int id = -1;
  String email = '';
  String name = '';
  Beneficiary beneficiary = Beneficiary.anonymous();
  String avatar = '';
  String username = '';
  bool firstLogin = true;
  String aboutMe = '';
  bool isDonor = false;
  String currency = '';
  String country = '';

  Map<String, dynamic> toJson() => <String, dynamic>{
        'id': id,
        'email': email,
        'name': name,
        'avatar': avatar,
        'username': username,
        'firstLogin': firstLogin,
        'about_me': aboutMe,
        'is_donor': isDonor,
        'currency': currency,
        'country': country.toLowerCase(),
      };

  User copyWith({
    int? id,
    String? email,
    String? name,
    String? lastName,
    String? avatar,
    String? username,
    bool? firstLogin,
    String? aboutMe,
    bool? isDonor,
    String? currency,
    String? country,
  }) {
    return User()
      ..id = id ?? this.id
      ..email = email ?? this.email
      ..name = name ?? this.name
      ..avatar = avatar ?? this.avatar
      ..username = username ?? this.username
      ..firstLogin = firstLogin ?? this.firstLogin
      ..aboutMe = aboutMe ?? this.aboutMe
      ..isDonor = isDonor ?? this.isDonor
      ..currency = currency ?? this.currency
      ..country = country ?? this.country;
  }
}

// I/flutter (27951): id
// I/flutter (27951): verified
// I/flutter (27951): email
// I/flutter (27951): beneficiary
// I/flutter (27951): is_donor
// I/flutter (27951): country
// I/flutter (27951): name
// I/flutter (27951): about_me
// I/flutter (27951): date_of_birth
// I/flutter (27951): avatar
// I/flutter (27951): is_first_login
// I/flutter (27951): reset_psw_code
// I/flutter (27951): created_at
// I/flutter (27951): updated_at
// I/flutter (27951): user
// I/flutter (27951): area_of_interest
