// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

class Wallet {
  Wallet(
    this.address,
    this.keystore,
  );

  Wallet.fromJson(Map<String, dynamic> json)
      : address = json['address'] as String,
        keystore = json['keystore'] as Map<String, dynamic>;

  final String address;

  final Map<String, dynamic> keystore;

  Map<String, dynamic> toJson() => <String, dynamic>{
        'address': address,
        'keystore': keystore,
      };
}

//TODO liquid Julien
class PreparedReceivingTransactionStats {
  PreparedReceivingTransactionStats(
    this.amount,
    this.fee,
    this.total,
  );

  PreparedReceivingTransactionStats.fromJson(Map<String, dynamic> json)
      : amount = json['amount'] as String,
        fee = json['fee'] as String,
        total = json['total'] as String;

  final String amount;

  final String fee;

  final String total;

  Map<String, dynamic> toJson() => <String, dynamic>{
        'amount': amount,
        'fee': fee,
        'total': total,
      };
}
