// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrxyDldzZc9GEsjvb-Y47-EtVElKxeNlw',
    appId: '1:265595937590:android:44172642403745d38e0997',
    messagingSenderId: '265595937590',
    projectId: 'dinasona',
    storageBucket: 'dinasona.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwaHo81gmMKbwfGeY6SzuXTYWL02-S4YA',
    appId: '1:265595937590:ios:55f748a83a4bea518e0997',
    messagingSenderId: '265595937590',
    projectId: 'dinasona',
    storageBucket: 'dinasona.firebasestorage.app',
    androidClientId:
        '265595937590-u3dd8krfii1c4u95bvildth7465k37rn.apps.googleusercontent.com',
    iosClientId:
        '265595937590-tkh1g1g28ild34s536kikeoqml13573r.apps.googleusercontent.com',
    iosBundleId: 'org.dinasona.dinasona',
  );
}
