// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch
import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';
import 'package:get/get.dart';
import 'package:is_first_run/is_first_run.dart';

import './util/constants.dart';
import 'firebase_options.dart';
import 'model/message.dart';
import 'pages/error/error_page.dart';
import 'pages/lost_connection/lost_connection_page.dart';
import 'pages/who_you_are.dart';
import 'service/localization_controller.dart';
import 'service/main_bindings.dart';
import 'service/network_service.dart';
import 'service/storage/storage_service.dart';
import 'service/theme_service.dart';
import 'util/util.dart';

bool isFirstRun = false;
Future<void> handleError(
  Object error,
  StackTrace? stack, {
  bool fatal = false,
  Iterable<Object> information = const <Object>[],
  bool async = false,
}) async {
  // Failed host lookup
  if (error.toString().contains('Failed host lookup')) {
    Get.put(NetworkService()).onInternetLostPage.value = true;
    await Get.to(() => const LostConnectionPage());
    if (error.toString().contains('No host specified in URI file:///')) {
      return;
    }

    // Check if the application is running on dev mode
    final bool devMode = bool.tryParse(
          const String.fromEnvironment(
            'DEV_MODE',
          ),
        ) ??
        false;

    final GetMaterialController currentController = Get.rootController;

    final String previousRoute = currentController.routing.previous;

    // if (Get.put(UserStateService()).user.value.id != -1) {
    //   FirebaseCrashlytics.instance.setUserIdentifier(
    //       Get.put(UserStateService()).user.value.id.toString());
    // }

    if (!devMode) {
      if (fatal) {
        // If you see fatal on the crashlytics, it was registered here
        await FirebaseCrashlytics.instance.recordError(
          error,
          stack,
          fatal: true,
          information: <Object>[
            'Current Route: ${Get.currentRoute}',
            'Previous Route:  $previousRoute',
            'Asynchronous: $async',
            // "User Id: ${Get.put(UserStateService()).user.value.id.toString()}",
            ...information,
          ],
        );

        if (getMaterialAppCalled) {
          await Get.to(() => ErrorPage(error: error));
        } else {
          // Try to exit app:
          // SystemChannels.platform.invokeMethod('SystemNavigator.pop');
        }
      } else {
        // If you see non fatal on the crashlytics, it was registered here
        await FirebaseCrashlytics.instance.recordError(
          error,
          stack,
          reason: 'a non-fatal error, this will be ignored',
          information: <Object>[
            'Current Route: ${Get.currentRoute}',
            'Previous Route:  $previousRoute',
            'Asynchronous: $async',
            // "User Id: ${Get.put(UserStateService()).user.value.id.toString()}",
            ...information,
          ],
        );
      }
    }
  }
}

void main() async {
  FlutterError.onError = (FlutterErrorDetails details) async {
    await handleError(
      details.exception,
      details.stack,
      fatal: true,
    );
  };

  await runZonedGuarded<Future<void>>(() async {
    final MainBindings mainBinding = MainBindings();
    await mainBinding.dependencies();
    WidgetsFlutterBinding.ensureInitialized();
    final WidgetsBinding widgetsBinding =
        WidgetsFlutterBinding.ensureInitialized();
    FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);
    // Initialize services:
    await initializeServices();

    Get.put<ThemeService>(ThemeService());
    final LocalizationController localizationController =
        Get.put(LocalizationController());
    await localizationController.init();
    FlutterNativeSplash.remove();

    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    }
    await SystemChrome.setPreferredOrientations(
      <DeviceOrientation>[DeviceOrientation.portraitUp],
    );
    isFirstRun = await IsFirstRun.isFirstRun();

    runApp(const MyApp());
  }, (Object error, StackTrace stack) async {
    debugPrint('Error caught by main zone');
    debugPrint(error.toString());
    debugPrint(stack.toString());

    await handleError(error, stack, fatal: true);
  });
}

Future<void> initializeServices() async {
  // Initialize services:
  await Get.find<StorageService>().init();
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    getMaterialAppCalled = true;
    return GetBuilder<LocalizationController>(
      builder: (LocalizationController localizationController) {
        //Start MaterialApp
        return GetMaterialApp(
          locale: localizationController.locale,
          translations:
              Messages(languages: localizationController.translations),
          debugShowCheckedModeBanner: DinasonaConstants.devMode,
          title: 'dinasona',
          initialRoute: '/',
          getPages: <GetPage<void>>[
            GetPage<void>(
              name: '/',
              page: () => const ChosePathPage(),
            ),
          ],
          theme: Get.put<ThemeService>(ThemeService()).themeData,
        );
        //End MaterialApp
      },
    );
  }
}
