// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch
import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_breez_liquid/flutter_breez_liquid.dart' as liquid_sdk;
import 'package:flutter_native_splash/flutter_native_splash.dart';
import 'package:get/get.dart';
import 'package:is_first_run/is_first_run.dart';

import './util/constants.dart';
import 'firebase_options.dart';
import 'model/auth_response.dart';
import 'model/message.dart';
import 'pages/error/error_page.dart';
import 'pages/login/donor_and_beneficiary/login_page.dart';
import 'pages/root/beneficiary_root_page.dart';
import 'pages/root/donor_root_page.dart';
import 'service/auth_service.dart';
import 'service/currency_conversion_service.dart';
import 'service/localization_controller.dart';
import 'service/logger_service.dart';
import 'service/main_bindings.dart';
import 'service/messaging_service.dart';
import 'service/network_service.dart';
import 'service/storage/storage_service.dart';
import 'service/theme_service.dart';
import 'service/user_state_service.dart';
import 'service/wallet_service.dart';
import 'theme/color.dart';
import 'util/util.dart';

bool isFirstRun = false;
Future<void> handleError(
  Object error,
  StackTrace? stack, {
  bool fatal = false,
  Iterable<Object> information = const <Object>[],
  bool async = false,
}) async {
  final GetMaterialController currentController = Get.rootController;

  final String previousRoute = currentController.routing.previous;

  if (Get.put(UserStateService()).user.value.id != -1) {
    await FirebaseCrashlytics.instance.setUserIdentifier(
      Get.put(UserStateService()).user.value.id.toString(),
    );
  }

  if (fatal) {
    // If you see fatal on the crashlytics, it was registered here
    await FirebaseCrashlytics.instance.recordError(
      error,
      stack,
      fatal: true,
      information: <Object>[
        'Current Route: ${Get.currentRoute}',
        'Previous Route:  $previousRoute',
        'Asynchronous: $async',
        'User Id: ${Get.put(UserStateService()).user.value.id}',
        ...information,
      ],
    );

    if (getMaterialAppCalled) {
      Get.put(LoggerService()).log(
        'Fatal error caught by main zone',
        stackTrace: stack,
        error: error,
      );
      unawaited(Get.to<void>(() => ErrorPage(error: error)));
    } else {
      // Try to exit app:
      await SystemChannels.platform.invokeMethod('SystemNavigator.pop');
    }
  } else {
    // If you see non fatal on the crashlytics, it was registered here
    await FirebaseCrashlytics.instance.recordError(
      error,
      stack,
      reason: 'a non-fatal error, this will be ignored',
      information: <Object>[
        'Current Route: ${Get.currentRoute}',
        'Previous Route:  $previousRoute',
        'Asynchronous: $async',
        'User Id: ${Get.put(UserStateService()).user.value.id}',
        ...information,
      ],
    );
  }
}

void main() async {
  FlutterError.onError = (FlutterErrorDetails details) async {
    await handleError(
      details.exception,
      details.stack,
      fatal: true,
    );
  };

  await runZonedGuarded<Future<void>>(() async {
    final MainBindings mainBinding = MainBindings();
    await mainBinding.dependencies();
    WidgetsFlutterBinding.ensureInitialized();
    final WidgetsBinding widgetsBinding =
        WidgetsFlutterBinding.ensureInitialized();
    FlutterNativeSplash.preserve(widgetsBinding: widgetsBinding);

    // Initialize services:
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform,
      );
    }

    await liquid_sdk.initialize();
    await initializeServices();

    Get.put<ThemeService>(ThemeService());
    final LocalizationController localizationController =
        Get.put(LocalizationController());
    await localizationController.init();
    FlutterNativeSplash.remove();

    await SystemChrome.setPreferredOrientations(
      <DeviceOrientation>[DeviceOrientation.portraitUp],
    );
    isFirstRun = await IsFirstRun.isFirstRun();

    if (isFirstRun) {
      try {
        await Get.find<StorageService>().secure.deleteAll();
      } catch (_) {}
    }

    final AuthService authService = Get.find<AuthService>();
    Widget initialPage = const LoginPage();

    final AuthResponse response = await authService.silentLogin();
    if (response.success) {
      await Get.find<LocalizationController>().getUserCurrencyFromBackend();
      await Get.find<WalletService>().connectToWalletAfterSignIn();

      final CurrencyConversionService currencyConversionService =
          Get.find<CurrencyConversionService>();

      await currencyConversionService.fetchUserTargetCurrencyRate(
        'usd',
      );
      await currencyConversionService.fetchConversionRateBTCUserCurrency();
      await currencyConversionService.fetchConversionRateBTCvsUSD();
      await currencyConversionService.fetchUserTargetCurrencyRate(
        'chf',
      );

      initialPage = Get.find<UserStateService>().user.value.isDonor
          ? const DonorRootPage()
          : const BeneficiaryRootPage();
    }
    Get.put<ThemeService>(ThemeService()).themeData;

    runApp(MyApp(initialPage: initialPage));
  }, (Object error, StackTrace stack) async {
    debugPrint('Error caught by main zone');
    debugPrint(error.toString());
    debugPrint(stack.toString());

    await handleError(error, stack, fatal: true);
  });
}

Future<void> initializeServices() async {
  // Initialize services:
  await Get.find<StorageService>().init();
  Get.find<AuthService>().init();
  await Get.put(MessagingService()).init();
  Get.put(NetworkService());
}

class MyApp extends StatelessWidget {
  const MyApp({required this.initialPage, super.key});
  final Widget initialPage;
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    getMaterialAppCalled = true;
    return GetBuilder<LocalizationController>(
      builder: (LocalizationController localizationController) {
        //Start MaterialApp
        return GetMaterialApp(
          locale: localizationController.locale,
          translations:
              Messages(languages: localizationController.translations),
          debugShowCheckedModeBanner: Constants.devMode,
          title: 'dinasona',
          home: initialPage,
          initialRoute: '/',
          theme: Get.put<ThemeService>(ThemeService()).themeData.copyWith(
                colorScheme: const ColorScheme.light(
                  primary: LightColor.ferngreen,
                  secondary: LightColor.amberglow,
                  error: LightColor.inferno,
                ),
                progressIndicatorTheme: const ProgressIndicatorThemeData(
                  color: LightColor.ferngreen,
                  linearTrackColor: LightColor.graphite,
                ),
              ),
        );
        //End MaterialApp
      },
    );
  }
}
