// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

class DinasonaConstants {
  static const String apiDomain = String.fromEnvironment('DATABASE_URL');
  static const String apiKey = String.fromEnvironment('DATABASE_API_KEY');
  static bool get devMode => apiDomain.contains('dev-');
}
