// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'package:flutter/material.dart';
import 'package:get/get.dart';

import '../service/logger_service.dart';
import '../service/theme_service.dart';
import '../theme/theme.dart';

class CustomScaffold extends StatelessWidget {
  const CustomScaffold({
    required this.body,
    super.key,
    this.bottomNavigationBar,
  });

  final Widget body;
  final Widget? bottomNavigationBar;

  @override
  Widget build(BuildContext context) {
    final CustomTheme dinasonaTheme = Get.put(ThemeService()).theme;
    return Scaffold(
      body: body,
      backgroundColor: dinasonaTheme.moonstone,
      bottomNavigationBar: bottomNavigationBar,
      floatingActionButton: FloatingActionButton(
        heroTag: null,
        onPressed: () {
          Get.find<LoggerService>().show();
        },
        backgroundColor: Colors.red,
        child: const Icon(Icons.logo_dev_rounded),
      ),
    );
  }
}
