// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'package:flutter/material.dart';
import 'package:gap/gap.dart';
import 'package:get/get.dart';

import '../../service/theme_service.dart';
import '../../theme/theme.dart';
import '../../theme/typography.dart';
import '../../util/util.dart';
import '../../widgets/custom_scaffold.dart';
import 'controller/error_controller.dart';

class ErrorPage extends GetView<ErrorController> {
  const ErrorPage({required this.error, super.key});

  final Object error;

  @override
  Widget build(BuildContext context) {
    Get.put(ErrorController());
    final CustomTheme theme = Get.put(ThemeService()).theme;

    return CustomScaffold(
      body: Padding(
        padding: EdgeInsets.symmetric(
          vertical: getRelativeHeight(70),
          horizontal: getRelativeWidth(20),
        ),
        child: Column(
          children: <Widget>[
            Image.asset(
              'assets/images/logos/dinasona_logo.png',
              scale: 2.5,
            ),
            Gap(
              getRelativeHeight(80),
            ),
            Text(
              'Ohh, no'.tr,
              style: CustomTypography.fromColor(theme.shadowed).k36Bold,
            ),
            Gap(getRelativeHeight(10)),
            Text(
              "Oops! It looks like we've hit a bump in the road. Don't worry though, Dinasona team is on it and we'll have things up and running smoothly again in no time. Thanks for your patience 💚 !",
              style: CustomTypography.fromColor(theme.graphite).k16Reg,
              textAlign: TextAlign.center,
            ),
          ],
        ),
      ),
    );
  }
}
