// This file has been automatically generated by Flutter Architect.
//
// Flutter Architect is a tool that generates boilerplate code for your Flutter projects.
// Flutter Architect was created at SayNode Operations AG by Yann Marti, Francesco Romeo and Pedro Gonçalves.
//
// https://saynode.ch

import 'package:get/get.dart';
import 'package:internet_connection_checker_plus/internet_connection_checker_plus.dart';

//import '../pages/lost_connection/lost_connection_page.dart';

class ConnectivityBaseService extends GetxService {
  Rx<InternetStatus> connectionStatus = InternetStatus.disconnected.obs;

  void init() {
    InternetConnection().onStatusChange.listen((InternetStatus status) {
      switch (status) {
        case InternetStatus.connected:
          connectionStatus.value = status;
        case InternetStatus.disconnected:
          connectionStatus.value = status;
        /* Get.to<void>(
            () => const LostConnectionPage(),
            transition: Transition.cupertino,
          ); */
      }
    });

    super.onInit();
  }

  Future<void> waitForNetworkConnection() async {
    await Future.doWhile(() async {
      await Future<void>.delayed(const Duration(milliseconds: 750));
      return connectionStatus.value != InternetStatus.connected;
    });
  }

  Future<bool> hasInternetConnection() async {
    return InternetConnection().hasInternetAccess;
  }
}
