

name: Linting Workflow

on: pull_request

jobs:
  build:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Setup Repository
        uses: actions/checkout@v2
      

      - id: set_var
        run: |
          content=`cat ./.fvm/fvm_config.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=fvmConfig::$content"

      - run: |
          flutterVersion=${{fromJson(steps.set_var.outputs.fvmConfig).flutterSdkVersion}}
          echo "VERSION=$flutterVersion" >> "$GITHUB_ENV"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: ${{ env.VERSION }}
      - run: flutter --version

      - name: Install Pub Dependencies
        run: flutter pub get

      - name: Verify Formatting
        run: dart format --output=none --set-exit-if-changed .
      - name: Analyze Project Source
        run: dart analyze --fatal-infos